### ISSUE TITLE
🪲 Bug Report - Incorrect acronym in ExpressRoute gateway

### ISSUE THREAD

**Issue by tksh164** [Azure/Azure-Proactive-Resiliency-Library#164]
## Describe the bug

The acronym for ExpressRoute gateway is `ergw` in the [CAF documentation](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations#networking). However, APRL uses `erg` as an acronym for ExpressRoute gateway.

Example: https://github.com/Azure/Azure-Proactive-Resiliency-Library/blob/main/docs/content/services/networking/expressroute-gateway/code/erg-1/erg-1.kql

Also, mismatching the acronym between the file name and query result because the KQL query returns the correct acronym `ergw` even if file name `erg-1.kql`.

https://github.com/Azure/Azure-Proactive-Resiliency-Library/blob/80962a4539e9ab3eb338b7eed512b1a71ef10806/docs/content/services/networking/expressroute-gateway/code/erg-1/erg-1.kql#L7

## To Reproduce

n/a

## Expected behaviour

The file and directory name align to CAF acronyms, also those matches with the query result. 

## Screenshots 📷

n/a

## Additional context

n/a

**Comment by oZakari** [comment]
Thanks @tksh164, if you want to include this in the same PR as your other bug, that would be appreciated. If you don't have the capacity, don't worry about it though 👍🏼
