### ISSUE TITLE
❓👂 Question/Feedback - NSG-1: Is this against NSGs or all Azure resources?

### ISSUE THREAD

**Issue by tksh164** [Azure/Azure-Proactive-Resiliency-Library#167]
## Question/Feedback

NSG-1 talk about NSGs or all Azure resources?

https://azure.github.io/Azure-Proactive-Resiliency-Library/services/networking/network-security-group/#nsg-1---configure-diagnostic-settings-for-all-azure-resources

> NSG-1 - Configure Diagnostic Settings for **_all Azure Resources_**

## Possible Answers/Solutions?

If NSG-1 is about NSG, it needs to fix the title to `NSG-1 - Configure Diagnostic Settings for all network security groups`.
If NSG-1 talk about all Azure resources, this recommendation should move to another category. `General` is better, I think.

**Comment by oZakari** [comment]
I agree, confusing with the wording. I think we'll probably end up just keeping the diagnostic setting for each service but update the wording. Determining diagnostic settings can be difficult to return with ARG for most resources, so we'll look this a bit more on our end.
