### ISSUE TITLE
🪲 Bug Report - ST-1: KQL file name not aligned to standard file name format

### ISSUE THREAD

**Issue by tksh164** [Azure/Azure-Proactive-Resiliency-Library#169]
## Describe the bug

ST-1 has two KQL files then one of two files has the non-standard file name format that has `.fix` suffix.

- st-1.kql
    - https://github.com/Azure/Azure-Proactive-Resiliency-Library/blob/main/docs/content/services/storage/storage-Account/code/st-1/st-1.kql

- **st-1.kql.fix**
    - https://github.com/Azure/Azure-Proactive-Resiliency-Library/blob/main/docs/content/services/storage/storage-Account/code/st-1/st-1.kql.fix

## To Reproduce

- n/a

## Expected behaviour

- Align to the standard file name format like `st-1.kql`.

## Screenshots 📷

None

## Additional context

None

**Comment by oZakari** [comment]
Hi @tksh164, the query files with the .fix suffix are the result of us going through all queries and validating whether or not the queries work, return expected results, and output correct columns/params. For any query that did not meet those criteria, we added the .fix prefix and changed the query within the APRL site to show that the query was under development. All queries that are working should only have on KQL file, E.g. st-1.kql.

**Comment by tksh164** [comment]
@oZakari - Got it, thanks.
