### ISSUE TITLE
👂 Feedback - DDoS IP Protection is available in East US 2 and West Europe regions

### ISSUE THREAD

**Issue by tksh164** [Azure/Azure-Proactive-Resiliency-Library#171]
## Feedback

In the VNET-2 guidance explains DDoS IP Protection NOT available in East US 2 and West Europe regions. But DDoS IP Protection is available in those regions currently.

- https://azure.github.io/Azure-Proactive-Resiliency-Library/services/networking/virtual-networks/#vnet-2---use-azure-ddos-standard-protection-plans-to-protect-all-public-endpoints-hosted-within-customer-virtual-networks

    > P.S. DDoS IP Protection is currently not available in East US 2 and West Europe regions.

The pricing is available in East US 2 and West Europe regions.

- [Azure DDoS Protection pricing](https://azure.microsoft.com/en-us/pricing/details/ddos-protection/)

Also, it could be configured.

East US 2:
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/1618784/cf625108-9497-4ce6-904f-6263ce84eb54)

West Europe:
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/1618784/e487a05f-e363-413c-a7ea-f2eaf9581d25)

## Possible Solutions?

Remove the following sentence from the guidance of VNET-2.

> P.S. DDoS IP Protection is currently not available in East US 2 and West Europe regions.

**Comment by oZakari** [comment]
Good find @tksh164, ideally this type of information should be linked to instead of referenced directly as well so we don't get out of sync with PG docs. I have opened PR removing the sentence.
