### ISSUE TITLE
🪲 Bug Report - VM-10: False positive result

### ISSUE THREAD

**Issue by tksh164** [Azure/Azure-Proactive-Resiliency-Library#183]
## Describe the bug

[The VM-10 query](https://github.com/Azure/Azure-Proactive-Resiliency-Library/blob/main/docs/content/services/compute/virtual-machines/code/vm-10/vm-10.kql) returns false positive result in the following situation because the query is matched NICs by the name. It should use resource ID instead of name to get stabilized result.

There are NICs that have the same name and they are in different resource groups:

- rg1
    - ***nic5678***: Accelerated networking ***Off***
- rg2
    - ***nic5678***: Accelerated networking ***On***

## To Reproduce

1. Setup to the following situation.

    - rg1
        - ***nic5678***: Accelerated networking ***Off***
    - rg2
        - ***nic5678***: Accelerated networking ***On***

2. Run the VM-10 query.

## Expected behavior

- VM-10 query returns correct result.
    - The query should use the resource ID of NIC instead of name to match.

## Screenshots 📷

There are two NICs that have the same name and they are in different resource groups. The first NIC's accelerated networking is disabled, the second NIC's accelerated networking is enabled.

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/1618784/fc5f0a45-e584-4bdd-80f6-348ec84d3002)

The VM-10 query returns both NICs as disabled accelerated networking even though one is enabled.

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/1618784/6ef35148-b375-4d37-adbc-10bdeb7405a9)

## Additional context

- None

**Comment by oZakari** [comment]
Hey @tksh164, assigned this to you and approved your PR. Thanks much!
