### ISSUE TITLE
👂 Feedback - VM-18: Policy name in param1 is not helpful

### ISSUE THREAD

**Issue by tksh164** [Azure/Azure-Proactive-Resiliency-Library#194]
## Feedback

The policy name as param1 of the result of the VM-18 is not helpful because it is difficult to find the actual policy from the value in param1.

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/1618784/9c92034b-ab3e-4897-acae-2491c1972de1)

## Possible Answers/Solutions?

Set a searchable value in Azure portal to param1.

**Comment by nekdima** [comment]
I have the same experience and observation with "VM-18".

**Comment by oZakari** [comment]
Thanks for confirming @nekdima, @tksh164 created a PR for this which has just been merged so should be good from here on out if you want to try the new query.
