### ISSUE TITLE
👂 Feedback - VM-18: "tags" in result came from policy state, not VM

### ISSUE THREAD

**Issue by tksh164** [Azure/Azure-Proactive-Resiliency-Library#195]
## Feedback

The `tags` column in the result of the VM-18 query came from policy state resources, not VM resources. In general, cannot assign tags to policy state resources, so, the `tags` column in the query result is always `null`.

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/1618784/739b38e4-5123-40d1-84ae-a2e895097543)

## Possible Answers/Solutions?

Retrieve tags column from VM resources.

**Comment by oZakari** [comment]
Hi @alisakina99, would you mind please removing the tags column from this query? You can just include it in your VMSS tags PR that is already open.
