### ISSUE TITLE
🪲 Bug Report - VM-20: Return incorrect result

### ISSUE THREAD

**Issue by tksh164** [Azure/Azure-Proactive-Resiliency-Library#196]
## Describe the bug

The [VM-20 query](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machines/#vm-20---enable-vm-insights) returns incorrect result. Because the VM extension installation state does not represent VM insights enabled, or not. 

## To Reproduce

1. Deploy an Azure Windows VM.
2. [Install `AzureMonitorWindowsAgent` extension](https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-manage#install) to the deployed Azure Windows VM.

The query result does not have the deployed Azure Windows VM even though VM insights is not enabled.

## Expected behavior

The query returns the correct result.

## Screenshots 📷

1. **Not enabled** VM insights on `vm6`, and it have the `AzureMonitorWindowsAgent` VM extension.

    ![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/1618784/53affa09-9e06-4fb3-a688-87e53aed69fa)
    
    ![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/1618784/e4f9eb4a-ad03-4704-890c-1f63ec19aca3)

    ![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/1618784/c1c4f274-4cdb-416f-8f9b-c72d523104e6)

    ![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/1618784/5151086c-2742-445f-9bb7-c43ee493dcad)

2. The query result does not have `vm6` even though VM insights is **not enabled**. (The result should include vm6 because VM insights is not enabled on the VM)

    ![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/1618784/3b702c2f-477d-4625-96c8-aca33a95c453)

## Additional context

None

**Comment by ejhenry** [comment]
Good catch @tksh164! I think we'll need to pull this query until we can identify a better approach to validating whether insights are enabled for a VM.

cc: @oZakari

**Comment by tksh164** [comment]
@ejhenry I agree with you.

I researched at how Azure portal gets VM Insights status in **Overview** tab in [Azure portal](https://portal.azure.com/#view/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/~/virtualMachines) using the Network tool of the browser's DevTools. As a result, I found that we need different approaches to Azure Monitor agent and Log Analytics agent. (But we can put those into a single ARG query eventually, I think)

**For VM Insights with Azure Monitor agent:**

- Data collection rules (DCRs) that use for MV Insights are include `Microsoft-InsightsMetrics` or `Microsoft-ServiceMap`.
    - If the DCR includes `Microsoft-InsightsMetrics`, VM Insights' Performance is enabled.
    - If the DCR includes `Microsoft-ServiceMap`, VM Insights' Service Map is enabled.
- DCRs and VMs can join using `Microsoft.Insights/dataCollectionRuleAssociations`.

The following ARG query is to get VMs that VM Insights *ENABLED* with Azure Monitor agent.

```sql
// VM Insights with Azure Monitor agent
Resources
| where type =~ "Microsoft.Insights/dataCollectionRules"
| extend
    isPerformanceEnabled = iif(properties.dataSources.performanceCounters contains "Microsoft-InsightsMetrics" and properties.dataFlows contains "Microsoft-InsightsMetrics", true, false),
    isMapEnabled = iif(properties.dataSources.extensions contains "Microsoft-ServiceMap" and properties.dataSources.extensions contains "DependencyAgent" and properties.dataFlows contains "Microsoft-ServiceMap", true, false)//,
    //workspaceResourceId = properties['destinations']['logAnalytics'][0]['workspaceResourceId'],
    //workspaceId = properties['destinations']['logAnalytics'][0]['workspaceId']
| where isPerformanceEnabled or isMapEnabled 
| project dcrName = name, isPerformanceEnabled, isMapEnabled, lowerCaseDcrId = tolower(id)
| join kind = leftouter (
    InsightsResources
    | where type =~ "Microsoft.Insights/dataCollectionRuleAssociations" and id has "Microsoft.Compute/virtualMachines"
    | project
        lowerCaseDcrIdOfAssociation = tolower(properties.dataCollectionRuleId),
        lowerCaseVmIdOfAssociation = tolower(substring(id, 0, indexof(id, "/providers/Microsoft.Insights/dataCollectionRuleAssociations/")))
    )
    on $left.lowerCaseDcrId == $right.lowerCaseDcrIdOfAssociation
| project dcrName, isPerformanceEnabled, isMapEnabled, lowerCaseVmIdOfAssociation
| join kind = leftouter (
    Resources
    | where type =~ "Microsoft.Compute/virtualMachines"
    | project vmName = name, vmId = id, vmTags = tags, lowerCaseVmId = tolower(id)
    )
    on $left.lowerCaseVmIdOfAssociation == $right.lowerCaseVmId
```

**For VM Insights with Log Analytics agent (Microsoft Monitoring agent):**

- Log Analytics solutions and Log Analytics workspaces can join on `properties.workspaceResourceId` and `id`.
- Microsoft Monitoring agent's VM extensions and Log Analytics workspaces can join on `properties.settings.workspaceId` and `properties.customerId`.
- The VM extension's ID includes the VM's ID. 

The following ARG query is to get VMs that VM Insights *ENABLED* with Log Analytics agent (Microsoft Monitoring agent).

```sql
// VM Insights with Log Analytics agent
Resources
| where type =~ "Microsoft.OperationsManagement/solutions" and (plan.product has "ServiceMap" or plan.product has "VMInsights")
| project lowerCaseWorkspaceResIdOfSolution = tolower(properties.workspaceResourceId)
| join kind = leftouter (
    Resources
    | where type =~ "Microsoft.OperationalInsights/workspaces"
    | project workspaceName = name, customerId = tolower(properties.customerId), lowerCaseWorkspaceResId = tolower(id)
    )
    on $left.lowerCaseWorkspaceResIdOfSolution == $right.lowerCaseWorkspaceResId
| join kind = leftouter (
    Resources
    | where type =~ "Microsoft.Compute/virtualMachines/extensions" and properties.type =~ "MicrosoftMonitoringAgent"
    | extend vmId = substring(id, 0, indexof(id, "/extensions/")), customerId = tolower(properties.settings.workspaceId)
    | extend vmName = parse_path(vmId).Filename
    | project vmName, vmId, customerId
    )
    on customerId
| project name = vmName, id = vmId, param1 = strcat("LogAnalyticsWorkspace: ", workspaceName)
```

Above queries are tested with [my test case](https://github.com/tksh164/aprl-testing/tree/main/services/compute/virtual-machines/test/vm-20).

**Comment by ReneHezser** [comment]
@tksh164 how about a two-step verification?
1. check for installed extensions
2. see if a VM is sending data to a LAW

For 1) I don't see a problem. As of [Virtual machine extension details](https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-manage?tabs=azure-portal#virtual-machine-extension-details) and [Did the extension install properly?](https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-troubleshoot#did-the-extension-install-properly) we need to check for extensions, for which we have queries.

For 2) I see some issues.

- What if the VM has not yet sent data to a LAW?
- What if the LAW is in a subscription that the query executor cannot access?

**Comment by tksh164** [comment]
@ReneHezser Thank you for reaching me.

For 1) I agree. The extension installation status is part of the criteria, I think too.

For 2)

> What if the VM has not yet sent data to a LAW?

From my research, this point depends on the kind of agents, I believe.

- For Azure Monitor agent, we can identify by DCR associations.
- For Log Analytics agent, we can identify by associate the VM extension's `properties.settings.workspaceId` and Log Analytics workspace's `properties.customerId`.

> What if the LAW is in a subscription that the query executor cannot access?

This point is difficult, and I'm not researched. Also, there is one more similar case that is cross-tenant data collection (more difficult).

In my opinion, those cases can be taken out of scope because it is prerequisite that the query executor can access all related resources. Also, I think, it is false positive, so, better than false negative. If found VMs as "Not enabled" even if enabled (by this reason), APRL users can going to investigate with actual environment configuration.

---

The expected query result should have VMs that do NOT meet all the criteria below, I think.

**For VM Insights with Azure Monitor agent**
The following is the criteria to whether VM Insights enabled or not, I believe. My above post covers 2 only.

1. The VM has the Azure Monitor agent at least. Also, the VM has the Dependency agent if Service Map enabled.
2. The VM is associated with VM Insights DCR. That DCR has `Microsoft-InsightsMetrics` at least.
    - Because [the VM Insights DCR has special data streams](https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-enable-overview#data-collection-rule) that `Microsoft-InsightsMetrics` and `Microsoft-ServiceMap`.
        > VM Insights automatically creates a DCR that includes a special data stream required for its operation.

**For VM Insights with Log Analytics agent (Microsoft Monitoring agent)**
The following is the criteria to whether VM Insights enabled or not, I believe. My above post covers all.

1. The VM has the Log Analytics agent. Also, the VM has the Dependency agent if Service Map enabled.
2. The Log Analytics agent is connected to Log Analytics workspace.
    - This can obtain by associate the VM extension's `properties.settings.workspaceId` and Log Analytics workspace's `properties.customerId`.
3. The Log Analytics workspace that VM connected to has VM Insights solutions (`VMInsights` and `ServiceMap`. `VMInsights` at least)

---

I have [the test case](https://github.com/tksh164/aprl-testing/tree/main/services/compute/virtual-machines/test/vm-20) for this recommendation (Windows only). This may help.

Also, I think that [Azure portal](https://portal.azure.com/#view/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/~/virtualMachines) is one of good indicators to the query is good, or not.

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/1618784/617fa9a8-0b66-4e12-a7eb-b74407a70684)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/1618784/e17a85a2-6785-4e7d-8499-0bfb981473f9)
