### ISSUE TITLE
💡 Feature Request - Automation Standards for PowerShell scripts

### ISSUE THREAD

**Issue by tksh164** [Azure/Azure-Proactive-Resiliency-Library#213]
## Describe the solution you'd like

[APRL has automation standards for Azure Resource Graph queries](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing/#automation-standards-for-recommendations). However, there are no standards for PowerShell scripts.

PowerShell script-based recommendations are necessary because some APRL recommendations are difficult to cover by ARG queries. So, we need automation standards for PowerShell scripts.

## Describe alternatives you've considered

The following is my proposal for the automation standards for PowerShell scripts.

---

**Automation Standards for PowerShell scripts**

1. All PowerShell scripts should have two comments at the top of the script, one comment stating `Azure PowerShell script` and another comment providing a description of the script results returned. For example:

    ```
    // Azure PowerShell script
    // Provides a list of Azure Container Registry resources that do not have soft delete enabled
    ```

2. Scripts should only return resources that do not adhere to the APRL recommendation. For example, if the recommendation is to enable soft delete for Azure Container Registries, the associated scripts should only return Azure Container Registry resources that do not have soft delete enabled.

3. Scripts should only include codes to return resources that do not adhere to the APRL recommendation. Scripts should not include the support code such as sign-in to Azure ([Connect-AzAccount](https://learn.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount), Login-AzAccount), subscription selection ([Set-AzContext](https://learn.microsoft.com/en-us/powershell/module/az.accounts/set-azcontext), Select-AzSubscription), etc. Those codes should be executed outside of the APRL recommendation PowerShell script.

4. The script should returned the result as an array of `PSCustomObject` data type, and each result object should only include the following properties:

    | Property Name | Data Type | Required | Information Returned (Example) | Description |
    |:---:|:---:|:---:|:---:|---|
    | recommendationId | string | Yes | aks-1 | The acronym of the Azure service that the query is returning results for, followed by the APRL recommendation number. |
    | name | string | Yes | test-aks | The resource name of the Azure resource that does not adher to the APRL recommendation. |
    | id | string | Yes | /subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/test-resource-group/providers/Microsoft.ContainerService/managedClusters/test-aks | The resource ID of the Azure resource that does not adhere to the APRL recommendation. |
    | tags | PSCustomObject | No | {"Environment":"Test","Department":"IT"} | Any relevant tags associated to the resource that does not adhere to the APRL recommendation. The data type should match the data type of `tags` in the result of ARG queries by [Search-AzGraph](https://learn.microsoft.com/en-us/powershell/module/az.resourcegraph/search-azgraph). If not set tags, set `$null`. |
    | param1 | string | No | networkProfile:kubenet | Any additional information that is necessary to provide clarification for the APRL recommendation. |
    | param2 | string | No | networkProfile:kubenet | Any additional information that is necessary to provide clarification for the APRL recommendation. |
    | param3 | string | No | networkProfile:kubenet | Any additional information that is necessary to provide clarification for the APRL recommendation. |
    | param4 | string | No | networkProfile:kubenet | Any additional information that is necessary to provide clarification for the APRL recommendation. |
    | param5 | string | No | networkProfile:kubenet | Any additional information that is necessary to provide clarification for the APRL recommendation. |

    ```powershell
    [PSCustomObject] @{
        recommendationId = 'aks-1'
        name             = $resource.Name
        id               = $resource.Id
        tags             = if ($resource.Tags) { [PSCustomObject] ([Hashtable] $resource.Tags) } else { $null }
        param1           = 'networkProfile:kubenet'
        param2           = 'networkProfile:kubenet'
        param3           = 'networkProfile:kubenet'
        param4           = 'networkProfile:kubenet'
        param5           = 'networkProfile:kubenet'
    }
    ```

---

## Additional context

I'm creating [helper scripts for APRL](https://github.com/tksh164/aprl-helper-scripts) that allow batch execution of the APRL's queries and PowerShell scripts together. Hard to implement unified automation if not defined automation standards for APRL PowerShell scripts. Probably, not only me that facing the similar situation.

**Comment by oZakari** [comment]
Hi @tksh164, sorry for the late response. I think this is a great thing to get added to the contribution guide. I'll make a few adjustments to the wording, but feel free to submit PR with what you have listed above. Thanks much!

**Comment by tksh164** [comment]
@oZakari Thanks. Will create a PR on this.
