### ISSUE TITLE
🪲 Bug Report - ST-3 flags Premium accounts for lack of access tier

### ISSUE THREAD

**Issue by nekdima** [Azure/Azure-Proactive-Resiliency-Library#297]
## Describe the bug

KQL query for ST-3 flags **Premium** storage accounts for lack of the access tier while there is no access tier setting available for Premium storage accounts and therefore I consider it to be a bug.

## To Reproduce

Steps to reproduce the behaviour:

Run KQL query gains Azure Storage Account - Premium tier.

```
resources
| where type =~'microsoft.storage/storageaccounts'
| where isnull(properties.accessTier)
| project recommendationId = 'st-3', name, id, param1="not defined - GeneralPurpose V1"
```

## Expected behaviour

Only STs of displayed tier without access tier specified (GPv1) should be displayed.

**Comment by tksh164** [comment]
Agree with @nekdima.

The test case for ST-3: https://github.com/tksh164/aprl-testing/tree/main/services/storage/storage-account/test/st-3

**Comment by tksh164** [comment]
@oZakari - Actually, the goal of [ST-3](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/storage/storage-account/#st-3---ensure-performance-tier-is-set-as-per-workload) is listing upgradeable storage accounts to GPv2 in my understanding. If my understanding is correct, I am going to update the ST-3 guidance and the ARG query.

- [Legacy storage account types](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview#legacy-storage-account-types)
