### ISSUE TITLE
🪲 Bug Report - Categories and services should be listed alphabetically

### ISSUE THREAD

**Issue by judyer28** [Azure/Azure-Proactive-Resiliency-Library#31]
## Describe the bug

The child page default order appears to be sorted by weight\time creation rather than alphabetically.  Adding a new category such as "Monitoring" puts the menu item in the side navigation at the bottom and puts the item at the bottom of the Azure Services page category list rather than sorting alphabetically.  See screen shot.

## To Reproduce

Steps to reproduce the behaviour:

1. Create a new service category
2. See category at bottom of list

## Expected behaviour

1.  New category should be shown alphabetically

## Screenshots 📷

<img width="407" alt="image" src="https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/60985418/a7d29fbc-1ddf-4fae-8502-dbee51b5b8e7">

## Additional context

Anything else we should know to help us troubleshoot this bug?

**Comment by lachaves** [comment]
Closed as requested by @oZakari
