### ISSUE TITLE
❓👂 Question/Feedback - What naming convention is being used for the services?

### ISSUE THREAD

**Issue by cmendible** [Azure/Azure-Proactive-Resiliency-Library#35]
## Question/Feedback

What is the naming convention used by APRL?  

Also, rule code / name are in the format: `<service abbreviation>-digit`. This causes issues if you want  to print an ordered list of rules from tools such as [Azure Quick Review](https://aka.ms/azqr) (i.e. `FW-10` will come on top of `FW-1`). 

## Possible Answers/Solutions?

Use the service abbreviation that we recommend as part of CAF [here](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations) as the new naming convention.

Rule code / name should follow the format: `<service abbreviation>-\d{3}$`. The samples below show some rule names for Azure Firewall:

* `AFW-001`
*  `AFW-010`
* `AFW-101`

**Comment by Dost2010** [comment]
APRL = Azure Proactive Resiliency Review- It is  a name of Program/Project so CAF naming convention would not apply here.

**Comment by oZakari** [comment]
Hi @cmendible, we should be using the abbreviations provided [here](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations) 

cc: @rodrigoaatmicrosoft

**Comment by cmendible** [comment]
> Hi @cmendible, we should be using the abbreviations provided [here](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations)
> 
> cc: @rodrigosantosms

Correct that is the same link I provided in the question. 

The abbreviations currently in use should be changed. Do I open a new issue as a result of this discussion?

**Comment by oZakari** [comment]
Apologies, I missed your reference to that link! We can close this issue out once the existing abbreviations are corrected.
