### ISSUE TITLE
🪲 Bug Report - ERC-3 returns the wrong recommendation ID

### ISSUE THREAD

**Issue by judyer28** [Azure/Azure-Proactive-Resiliency-Library#410]
## Describe the bug

[ERC-3](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/networking/expressroute-circuits/#erc-3---ensure-both-connections-of-an-expressroute-circuit-are-configured-in-active-active-mode) is returning the wrong recommendation ID.  See the following from the ARG query:

| project recommendationId = **"erc-1**", name, id, tags, ...

## To Reproduce

NA

## Expected behaviour

Return recommendation ID erc-3

## Screenshots 📷

NA

## Additional context

NA

**Comment by ejhenry** [comment]
#420

**Comment by ejhenry** [comment]
Fix merged.
