### ISSUE TITLE
🪲 Bug Report - AGW-9 returns the wrong recommendation ID

### ISSUE THREAD

**Issue by judyer28** [Azure/Azure-Proactive-Resiliency-Library#416]
## Describe the bug

[AGW-9](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/networking/application-gateway/#agw-9---ensure-application-gateway-subnet-is-using-a-24-subnet-mask) is returning the wrong recommendation ID.  See the following from the ARG query:

| project recommendationID = "**agw-8**", name, id, tags, ...

## To Reproduce

NA

## Expected behaviour

Return ID agw-9

## Screenshots 📷

NA.

## Additional context

NA

**Comment by ejhenry** [comment]
fixed in #413
