### ISSUE TITLE
🪲 Bug Report - ANF-3 does not catch no availability zone if it is null 

### ISSUE THREAD

**Issue by judyer28** [Azure/Azure-Proactive-Resiliency-Library#421]
## Describe the bug

If you create a new ANF volume with no zone, it will put the following in the resource JSON:
"zones": []

If you populate or specify the zone then it will put something like the following in the resource JSON:
    "zones": [
        "3"
    ]

I am also seeing situations where the zone is not referenced at all anywhere in the JSON.  I am unsure the cause of this situation.  However, this means the query is not catching these volumes with no zones because the query does the following check:
| where zones == "[]"

I suggest changing this query to check the following conditions instead:
| where array_length(zones) == 0 or isnull(zones)

That should catch both scenarios where no zone has been set.

## To Reproduce

Not sure how this situation of zone field not populated into resource JSON occurs.

## Expected behaviour

The recommendation should catch all volumes without zones.

## Screenshots 📷

NA

## Additional context

NA

**Comment by tksh164** [comment]
@judyer28 Thank you for pointing this. a PR created for this point.
