### ISSUE TITLE
🪲 Bug Report - ERGW-1 including ExpressRoute gateway even though it has two connections to circuits from different peering locations

### ISSUE THREAD

**Issue by judyer28** [Azure/Azure-Proactive-Resiliency-Library#425]
## Describe the bug

I have an ExpressRoute Gateway with connections to circuits from two different peering locations, but the query is still capturing it as part of the conditions for the query. 

## Expected behaviour

If the gateway has 2 connections from 2 separate peering locations it should not be caught by the query.

## Additional context
@ejhenry

**Comment by ejhenry** [comment]
cc @jchancellor-ms
