### ISSUE TITLE
🪲 Bug Report - ERGW-2 is returning the wrong recommendation ID

### ISSUE THREAD

**Issue by judyer28** [Azure/Azure-Proactive-Resiliency-Library#433]
## Describe the bug

[ERGW-2](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/networking/expressroute-gateway/#ergw-2---use-zone-redundant-gateway-skus) - Use Zone-redundant gateway SKUs is returning the wrong recommendation ID from the query.  See line in query:
| project recommendationId = "**ergw-1**", name, id, tags, ...

## To Reproduce

Steps to reproduce the behaviour:

NA

## Expected behaviour

Return ID ERGW-2

## Screenshots 📷

NA

## Additional context

NA

**Comment by tksh164** [comment]
Thank you @judyer28 for your report. A PR was created to fix it.

**Comment by tksh164** [comment]
Fixed on #434
