### ISSUE TITLE
🪲 Bug Report - KV-5 query returns incorrect results

### ISSUE THREAD

**Issue by yahanda** [Azure/Azure-Proactive-Resiliency-Library#59]
## Describe the bug

The Resource Graph Query cannot return whether the diagnostic setting is enabled.
Since ```properties.diagnosticSettings``` does not exist on Key Vault, the query always returns all Key Vaults even if diagnostic logs are set.

## To Reproduce

Steps to reproduce the behaviour:

1. Run KQL. It will list all Key Vaults even if diagnostic logs are set because the following condition would always evaluate to true.
```
| where Diag = (isempty (properties.diagnosticSettings))
```

## Expected behaviour

The query should return a list of Key Vaults that do not have diagnostic settings enabled.

## Screenshots 📷

If applicable, add screenshots to help explain your problem. Please feel free to blur/cover any sensitive information.

## Additional context

There seems to be no way to return desired results by KQL at present. In order to avoid confusion, it would be better to remove the query until the feature is available.

**Comment by maheshbenke** [comment]
@yahanda  Agreed , Updated with the Query. Will follow up to see if we can improve this.
