### ISSUE TITLE
🪲 Bug Report - Traffic Manager missing from services list and App Gateway queries no longer show

### ISSUE THREAD

**Issue by judyer28** [Azure/Azure-Proactive-Resiliency-Library#88]
## Describe the bug

Traffic Manager is no longer visible in the list of services and when going to the App GW page, the ARG queries no longer show.

## To Reproduce

Steps to reproduce the behaviour:

1. Go to https://azure.github.io/Azure-Proactive-Resiliency-Library/services/networking/
2. Traffic Manager is not listed.
3. Go to https://azure.github.io/Azure-Proactive-Resiliency-Library/services/networking/application-gateway/
4. Queries are missing

## Expected behaviour

Traffic Manager listed and App gateway queries available.

## Screenshots 📷

<img width="365" alt="image" src="https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/60985418/1ed4cecd-200e-4bfa-bca1-f06d6f564fb8">

<img width="772" alt="image" src="https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/60985418/754c7c46-5cd9-40f6-8410-bca6a777aca4">

## Additional context

Anything else we should know to help us troubleshoot this bug?

**Comment by oZakari** [comment]
Think this might have to do with build specified in the hugo-site-fbuild.yml workflow as everything looks correct locally. Seems to be caching stuff or possibly need to add the --cleanDestinationDir flag.
